name: build-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VER: 10

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VER }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VER }}
    - run: yarn install
    - run: yarn test
    - run: yarn build